export enum Currencies {
   CAD = 'CAD',
   HKD = 'HKD',
   ISK = 'ISK',
   PHP = 'PHP',
   DKK = 'DKK',
   HUF = 'HUF',
   CZK = 'CZK',
   GBP = 'GBP',
   RON = 'RON',
   SEK = 'SEK',
   IDR = 'IDR',
   INR = 'INR',
   BRL = 'BRL',
   RUB = 'RUB',
   HRK = 'HRK',
   JPY = 'JPY',
   THB = 'THB',
   CHF = 'CHF',
   EUR = 'EUR',
   MYR = 'MYR',
   BGN = 'BGN',
   TRY = 'TRY',
   CNY = 'CNY',
   NOK = 'NOK',
   NZD = 'NZD',
   ZAR = 'ZAR',
   USD = 'USD',
   MXN = 'MXN',
   SGD = 'SGD',
   AUD = 'AUD',
   ILS = 'ILS',
   KRW = 'KRW',
   PLN = 'PLN'
}

export interface CurrenciesResponse {
   rates: {
      CAD: number,
      HKD: number,
      ISK: number,
      PHP: number,
      DKK: number,
      HUF: number,
      CZK: number,
      GBP: number,
      RON: number,
      SEK: number,
      IDR: number,
      INR: number,
      BRL: number,
      RUB: number,
      HRK: number,
      JPY: number,
      THB: number,
      CHF: number,
      EUR: number,
      MYR: number,
      BGN: number,
      TRY: number,
      CNY: number,
      NOK: number,
      NZD: number,
      ZAR: number,
      USD: number,
      MXN: number,
      SGD: number,
      AUD: number,
      ILS: number,
      KRW: number,
      PLN: number
   };
   base: string; // TRY
   date: string; // 2019-09-13
}
