export enum Currencies {
   AED = 'AED',
   AFN = 'AFN',
   ALL = 'ALL',
   AMD = 'AMD',
   AOA = 'AOA',
   ARS = 'ARS',
   AUD = 'AUD',
   AZN = 'AZN',
   BDT = 'BDT',
   BGN = 'BGN',
   BHD = 'BHD',
   BIF = 'BIF',
   BIH = 'BIH',
   BND = 'BND',
   BOB = 'BOB',
   BRL = 'BRL',
   BSD = 'BSD',
   BTC = 'BTC',
   BWP = 'BWP',
   BYR = 'BYR',
   CAD = 'CAD',
   CDF = 'CDF',
   CHF = 'CHF',
   CLP = 'CLP',
   CNY = 'CNY',
   COP = 'COP',
   CRC = 'CRC',
   CUC = 'CUC',
   CVE = 'CVE',
   CZK = 'CZK',
   DJF = 'DJF',
   DKK = 'DKK',
   DOP = 'DOP',
   DZD = 'DZD',
   EGP = 'EGP',
   ERN = 'ERN',
   ETB = 'ETB',
   ETH = 'ETH',
   EUR = 'EUR',
   FJD = 'FJD',
   GBP = 'GBP',
   GEL = 'GEL',
   GHS = 'GHS',
   GMD = 'GMD',
   GNF = 'GNF',
   GTQ = 'GTQ',
   GYD = 'GYD',
   HKD = 'HKD',
   HNL = 'HNL',
   HRV = 'HRV',
   HTG = 'HTG',
   HUF = 'HUF',
   IDR = 'IDR',
   ILS = 'ILS',
   INR = 'INR',
   IQD = 'IQD',
   IRR = 'IRR',
   ISK = 'ISK',
   JMD = 'JMD',
   JOD = 'JOD',
   JPY = 'JPY',
   KES = 'KES',
   KGS = 'KGS',
   KHR = 'KHR',
   KMF = 'KMF',
   KRW = 'KRW',
   KYD = 'KYD',
   KZT = 'KZT',
   LAK = 'LAK',
   LBP = 'LBP',
   LKR = 'LKR',
   LRD = 'LRD',
   LSL = 'LSL',
   LTC = 'LTC',
   LYD = 'LYD',
   MAD = 'MAD',
   MDL = 'MDL',
   MGA = 'MGA',
   MKD = 'MKD',
   MMK = 'MMK',
   MNT = 'MNT',
   MOP = 'MOP',
   MUR = 'MUR',
   MVR = 'MVR',
   MWK = 'MWK',
   MXN = 'MXN',
   MYR = 'MYR',
   MZN = 'MZN',
   NAD = 'NAD',
   NGN = 'NGN',
   NIO = 'NIO',
   NOK = 'NOK',
   NPR = 'NPR',
   NZD = 'NZD',
   OMR = 'OMR',
   PAB = 'PAB',
   PEN = 'PEN',
   PGK = 'PGK',
   PHP = 'PHP',
   PKR = 'PKR',
   PLN = 'PLN',
   PYG = 'PYG',
   QAR = 'QAR',
   RON = 'RON',
   RSD = 'RSD',
   RUB = 'RUB',
   RWF = 'RWF',
   SAR = 'SAR',
   SCR = 'SCR',
   SDG = 'SDG',
   SEK = 'SEK',
   SGD = 'SGD',
   SLL = 'SLL',
   SOS = 'SOS',
   SRD = 'SRD',
   SSP = 'SSP',
   STD = 'STD',
   SVC = 'SVC',
   SYP = 'SYP',
   SZL = 'SZL',
   THB = 'THB',
   TJS = 'TJS',
   TMT = 'TMT',
   TND = 'TND',
   TRY = 'TRY',
   TTD = 'TTD',
   TWD = 'TWD',
   TZS = 'TZS',
   UAH = 'UAH',
   UGX = 'UGX',
   URY = 'URY',
   USD = 'USD',
   UZS = 'UZS',
   VND = 'VND',
   XAF = 'XAF',
   XOF = 'XOF',
   XPF = 'XPF',
   XRP = 'XRP',
   YER = 'YER',
   ZAR = 'ZAR'
}

export interface CurrenciesResponse {
   data: {
      AED: number,
      AFN: number,
      ALL: number,
      AMD: number,
      AOA: number,
      ARS: number,
      AUD: number,
      AZN: number,
      BDT: number,
      BGN: number,
      BHD: number,
      BIF: number,
      BIH: number,
      BND: number,
      BOB: number,
      BRL: number,
      BSD: number,
      BTC: number,
      BWP: number,
      BYR: number,
      CAD: number,
      CDF: number,
      CHF: number,
      CLP: number,
      CNY: number,
      COP: number,
      CRC: number,
      CUC: number,
      CVE: number,
      CZK: number,
      DJF: number,
      DKK: number,
      DOP: number,
      DZD: number,
      EGP: number,
      ERN: number,
      ETB: number,
      ETH: number,
      EUR: number,
      FJD: number,
      GBP: number,
      GEL: number,
      GHS: number,
      GMD: number,
      GNF: number,
      GTQ: number,
      GYD: number,
      HKD: number,
      HNL: number,
      HRV: number,
      HTG: number,
      HUF: number,
      IDR: number,
      ILS: number,
      INR: number,
      IQD: number,
      IRR: number,
      ISK: number,
      JMD: number,
      JOD: number,
      JPY: number,
      KES: number,
      KGS: number,
      KHR: number,
      KMF: number,
      KRW: number,
      KYD: number,
      KZT: number,
      LAK: number,
      LBP: number,
      LKR: number,
      LRD: number,
      LSL: number,
      LTC: number,
      LYD: number,
      MAD: number,
      MDL: number,
      MGA: number,
      MKD: number,
      MMK: number,
      MNT: number,
      MOP: number,
      MUR: number,
      MVR: number,
      MWK: number,
      MXN: number,
      MYR: number,
      MZN: number,
      NAD: number,
      NGN: number,
      NIO: number,
      NOK: number,
      NPR: number,
      NZD: number,
      OMR: number,
      PAB: number,
      PEN: number,
      PGK: number,
      PHP: number,
      PKR: number,
      PLN: number,
      PYG: number,
      QAR: number,
      RON: number,
      RSD: number,
      RUB: number,
      RWF: number,
      SAR: number,
      SCR: number,
      SDG: number,
      SEK: number,
      SGD: number,
      SLL: number,
      SOS: number,
      SRD: number,
      SSP: number,
      STD: number,
      SVC: number,
      SYP: number,
      SZL: number,
      THB: number,
      TJS: number,
      TMT: number,
      TND: number,
      TRY: number,
      TTD: number,
      TWD: number,
      TZS: number,
      UAH: number,
      UGX: number,
      URY: number,
      USD: number,
      UZS: number,
      VND: number,
      XAF: number,
      XOF: number,
      XPF: number,
      XRP: number,
      YER: number,
      ZAR: number;
   };
   query: {
      apikey: string,
      base_currency: Currencies;
      timestamp: number;
   };
}
